version: "3.7"

volumes:
  postgres: {}

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - .:/app:delegated

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: howl
      POSTGRES_PASSWORD: howl
      POSTGRES_DB: howl
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
